Repository A7-TC2-TeamCode200/MRLA, pull requests merged in 2022-12, with the labels that each got.

#3 Feat : 프로필(Read, Update) 기능 구현
  users/admin.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#12 Feat: 댓글 수정/삭제 기능 추가
  foods/urls.py
  foods/views.py
Labels: enhancement

#13 Feat : 프로필, AI 메뉴 추천 시스템, 고객 센터
  .gitignore
  MRLA/urls.py
  foods/admin.py
  foods/collaborative_filtering.py
  foods/fixtures_data.json
  foods/foods.csv
  foods/likes.csv
  foods/loader.py
  foods/models.py
  foods/serializers.py
  foods/urls.py
  foods/views.py
  posts/serializers.py
  posts/urls.py
  posts/views.py
  users/admin.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#19 Fix : Merge 이후 버그 수정
  foods/models.py
  foods/serializers.py
  foods/urls.py
  foods/views.py
  posts/admin.py
  posts/models.py
  posts/serializers.py
  posts/urls.py
  posts/views.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: bug

#21 Feat : 프로필 페이지 기능 추가 및 Food 모델 수정
  MRLA/urls.py
  foods/collaborative_filtering.py
  foods/fixtures.json
  foods/foods.csv
  foods/loader.py
  foods/models.py
  foods/serializers.py
  foods/urls.py
  foods/views.py
  posts/models.py
  posts/serializers.py
  posts/urls.py
  posts/views.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: bug, enhancement

#25 Feat : 커뮤니티 게시글 검색 기능 추가
  posts/serializers.py
  posts/urls.py
  posts/views.py
Labels: enhancement

#31 Docs : 데이터셋 내용 추가
  .gitignore
  foods/fixtures.json
  foods/foods.csv
  foods/likes.csv
  foods/loader.py
Labels: enhancement

#38 서버 배포를 위한 최종 PR
  MRLA/settings.py
  foods/likes.csv
  foods/serializers.py
  posts/serializers.py
  posts/views.py
  users/admin.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#40 Fix : 고객센터 게시글 작성자 표기 수정
  posts/serializers.py
Labels: enhancement
